CREATE TABLE AddressCandies
(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
Addr TEXT NOT NULL, 
Candies TEXT NOT NULL,
FOREIGN KEY (Addr) REFERENCES Factories(Addr),
FOREIGN KEY (Candies) REFERENCES CandyTypes(Name)
);